### ISSUE TITLE
Have you compared the performance and effect with RIFE?

### ISSUE THREAD

**Issue by KevenLee** [tarun005/FLAVR#10]
Thanks for your greate jobs! 
Have you compared the performance and effect with RIFE?

**Comment by tarun005** [comment]
We want to note a couple of differences wrt RIFE. Firstly, RIFE is specifically designed for 2x interpolation, while our method FLAVR is capable of single shot multi frame prediction (for any x), so it is much faster than RIFE.  Secondly, RIFE requires reliable optical flow estimation network, while FLAVR does not make any such assumptions during training or inference making it simple to train and deploy. We did not compare the performance as both are contemporary works.

**Comment by Tsubajashi** [comment]
quality is quite a bit better, but pretty slow - it also wants a huge amount of vram for HD Videos and up.
its worth the wait.

**Comment by HeylonNHP** [comment]
My own comparisons against RIFE show that RIFE is much faster, and often produces better output.
Maybe FLAVR just needs time to mature.

**Comment by n00mkrad** [comment]
Currently FLAVR's only strength is that higher factors than 2x have no quality loss as it's not recursive.

Everything else is a side- or downgrade, especially the need for a 500mb model for every factor.

**Comment by adahbingee** [comment]
Tested that RIFE v2.4 is much more faster.
Does flow-free structure trade-off using 3D-conv may cause GPU inefficient?

**Comment by KevenLee** [comment]
> My own comparisons against RIFE show that RIFE is much faster, and often produces better output.
> Maybe FLAVR just needs time to mature.


I have similar results, I run FLAVR model with nvidia T4, 3.02 second/frame[resolution: w 720, h 1080], and the result is not as good as RIFE. The FLAVR inserted frame has ghost images and is more blurred, and looks clear->blur->clear->blur ....

**Comment by tarun005** [comment]
The major bottleneck for video interpolation using FLAVR is the CPU <- >GPU <-> CPU transfer of 4 frames (RIFE requires just two) which takes ~92% of the time iirc. The inference time, however, is fastest for FLAVR.

**Comment by hzwer** [comment]
Hi, I'm the main developer of RIFE. We have some suggestions for you if you have interests in making an interpolation applications :)
1. Use perceptual loss and strong data augmentation to train a new model, and it will be much better for visual effects.
2. Use multithreading to process video. You can refer to our code: https://github.com/hzwer/arXiv2020-RIFE/blob/main/inference_video.py

BTW, the newest version of RIFE paper cites FLAVR although we haven't done a performance comparison yet. We really appreciate your work.

**Comment by rsjjdesj** [comment]
> > My own comparisons against RIFE show that RIFE is much faster, and often produces better output.
> > Maybe FLAVR just needs time to mature.
> 
> I have similar results, I run FLAVR model with nvidia T4, 3.02 second/frame[resolution: w 720, h 1080], and the result is not as good as RIFE. The FLAVR inserted frame has ghost images and is more blurred, and looks clear->blur->clear->blur ....

Are there any sample images that you can share which show these artifacts.

**Comment by KevenLee** [comment]
> Are there any sample images that you can share which show these artifacts.

Sorry，since the data may involve some privacy issues, it cannot be sent publicly. I can send it to your private mailbox

**Comment by rsjjdesj** [comment]
> > Are there any sample images that you can share which show these artifacts.
> 
> Sorry，since the data may involve some privacy issues, it cannot be sent publicly. I can send it to your private mailbox

I understand. Trying to find if I can PM to you via gihub.
