### ISSUE TITLE
Questions about the inference time

### ISSUE THREAD

**Issue by GreyZzzzzzXh** [tarun005/FLAVR#14]
Hi, thanks for your interesting work!
I tested the inference time on vimeo90K_septuplet using your script, and i got the time is 0.004 s. It seems too fast?
I modified the code and tested again, and the time I got is 0.195 s.
![image](https://user-images.githubusercontent.com/35633199/112121589-5e977080-8bfa-11eb-91c3-57ba106f54d9.png)
![image](https://user-images.githubusercontent.com/35633199/112121719-81c22000-8bfa-11eb-95fb-59e6aa8be329.png)
So, I wonder how the time in your paper was tested?

**Comment by tarun005** [comment]
The major bottleneck in our model is the CPU/GPU transfer of 4 input frames, which takes a major amount of time, and calling cuda synchronous will also wait for all the transfer to complete. So for all the baseline models (including ours), we only measure the forward transfer time and ignore the cuda transfer time, which gets reflected in the cuda.synchronous calls. You are right that this is not an accurate reflection of the total computation time. More details on our bench marking process is provided in our paper.

**Comment by GreyZzzzzzXh** [comment]
Thanks for your reply. 
I call the first `torch.cuda.synchronous() `after `images = [img_.cuda() for img_ in images]`, it will wait for all data to be transferred to GPU, so the  transfer time will not be recorded, I think.
What I want to say is that CUDA calls are asynchronously, so only the `time()` function cannot get the correct inference time.
https://discuss.pytorch.org/t/how-to-get-forward-time/25158
Feel free to point out if I am wrong :)

**Comment by tarun005** [comment]
You are right. Thanks for bringing this to our notice. We will correct the benchmarking script and update the inference times in the paper.

**Comment by laomao0** [comment]
> You are right. Thanks for bringing this to our notice. We will correct the benchmarking script and update the inference times in the paper.

In this paper, it is 384x faster than the current most accurate method., so now?

**Comment by labb783** [comment]
ok, i think the paper should be rejected. The paper's main contribution is a fast speed. Now, it becomes a false promotion.

**Comment by Astrostellar** [comment]
Hi, could you please share the pretrained model? The current links seem to be unavailable. Thanks a lot!
