### ISSUE TITLE
How to use your model to predict the optical flow?

### ISSUE THREAD

**Issue by jzzsc** [tarun005/FLAVR#19]
Sorry to bother
Is there any code for predicting the optical flow based on your model?
I will appreciate it so much

**Comment by tarun005** [comment]
We used the code available here https://github.com/ClementPinard/FlowNetPytorch .
We first pretrain a model on Vimeo, drop the last prediction layer, attach another prediction layer for optical flow, and then train it on Sintel datasets. Results on 5-fold cross validation are provided in Table 6 in the paper.

**Comment by jzzsc** [comment]
> We used the code available here https://github.com/ClementPinard/FlowNetPytorch .
> We first pretrain a model on Vimeo, drop the last prediction layer, attach another prediction layer for optical flow, and then train it on Sintel datasets. Results on 5-fold cross validation are provided in Table 6 in the paper.

Thank you for your kind reply.
Dose it seem that I can use your pretrained model directly to predict the optical flow? (based on your Chapter 6 of the paper)
So, can I regard and use it as a faster and new method for optical flow prediction?

**Comment by jzzsc** [comment]
> We used the code available here https://github.com/ClementPinard/FlowNetPytorch .
> We first pretrain a model on Vimeo, drop the last prediction layer, attach another prediction layer for optical flow, and then train it on Sintel datasets. Results on 5-fold cross validation are provided in Table 6 in the paper.

Thank you so much for your reply.
But I am still confused about how to use FLAVR as a faster method for optical flow prediction (Capter 6 in the paper). The input is 2CxHxWx3 figures, and the output is (k-1)xHxWx3 figures in the FLAVR architecture. Where does it calculate the optical flow (like EV-flow net)?

**Comment by tarun005** [comment]
We drop the last output layer from FLAVR, and add a _new_ prediction layer, which predicts the x and y components of the optical flow, and _retrain_ it on a new flow datasets, like Sintel.

**Comment by jzzsc** [comment]
> We drop the last output layer from FLAVR, and add a _new_ prediction layer, which predicts the x and y components of the optical flow, and _retrain_ it on a new flow datasets, like Sintel.

Thank you!
