### ISSUE TITLE
error with there is no sep_trainlist.txt

### ISSUE THREAD

**Issue by AugustLee93** [tarun005/FLAVR#2]
Hi there,

When Im trying to run the test.py with the pretrained model that you privided, I got an error is that it show there is NOT a directory : xxxxxx/sep_trainlist.txt (my input data path). Can you tell me how to fix this ? Thank you

**Comment by tarun005** [comment]
Please download the Vimeo-90K septuplet dataset from the official source. 
http://data.csail.mit.edu/tofu/dataset/vimeo_septuplet.zip . There should be a sep_trainlist.txt in there.

**Comment by AugustLee93** [comment]
> Please download the Vimeo-90K septuplet dataset from the official source.
> http://data.csail.mit.edu/tofu/dataset/vimeo_septuplet.zip . There should be a sep_trainlist.txt in there.

Thanks!
