### ISSUE TITLE
Testing result on vimeo90k_septuplet

### ISSUE THREAD

**Issue by silence-moon** [tarun005/FLAVR#25]
Hello, my friend! I tested the model with pretrained model 'FLAVR_4x.pth' (yours) and dataset 'vimeo90k_septuplet', and the result of psnr I had got was 28.376122. I don't konw why it occurs.

![](https://user-images.githubusercontent.com/48373941/120947205-8914b680-c771-11eb-8435-26afed0ed8da.png)

**Comment by tarun005** [comment]
You cannot do 4x interpolation with septuplets. You need at least 13 consecutive frames, refer section 3 of our paper for the sampling procedure we used.

**Comment by silence-moon** [comment]
Thanks for your answer. When I use the model of 2x, the value of PSNR reaches 36.30.

**Comment by Astrostellar** [comment]
Hi, could you please share the pretrained model? The current links seem to be unavailable. Thanks a lot!
