### ISSUE TITLE
periodic pause of interpolated video

### ISSUE THREAD

**Issue by XiaoyuShi97** [tarun005/FLAVR#27]
https://user-images.githubusercontent.com/25840016/121840789-8c7ae580-cd0f-11eb-87f6-ab40ab5b5125.mp4

https://user-images.githubusercontent.com/25840016/121840821-a3213c80-cd0f-11eb-967b-8265f38789bf.mp4

Hi,

I am using pretrained 8x model to interpolate the demo sprite video as shown on the project homepage. But I find that it seems to "pause" per second. Do you know why? Thx!

**Comment by XiaoyuShi97** [comment]
Hi. I find that this happens when the FPS of input video is not 30. But I do not identify which part of the code leads to that.

**Comment by hzwer** [comment]
If you check the origin video frame by frame, you will notice that there is 1 frame pause in every five frames. You need to filter out these frames first. 
For your reference, https://github.com/hzwer/arXiv2020-RIFE/blob/9069a09cc3e9b9b06a4c4937fc2081f14e1199af/inference_video.py#L218

**Comment by XiaoyuShi97** [comment]
Hi hzwer, thx a lot! BTW, rife is a great work.
