### ISSUE TITLE
Blur output

### ISSUE THREAD

**Issue by around-star** [tarun005/FLAVR#28]
Input - 

https://user-images.githubusercontent.com/55460763/121847306-fd1d0480-cd05-11eb-8c8b-7343bdc5718c.mp4

Output - 

https://user-images.githubusercontent.com/55460763/121847470-3c4b5580-cd06-11eb-9bc5-d9a95657b20c.mp4

Hey @tarun005 , I used the 8x pretrained model on this video. The output seems blurry mostly at the edges. Can this be improved?

**Comment by around-star** [comment]
Not sure why I cant add the input image but you can get it here
[cat video](https://drive.google.com/file/d/1ZCr6HTrNu8f6T-nyIbToYXHMOKU88f7P/view?usp=sharing)

**Comment by tarun005** [comment]
We are currently acquiring more data and training larger and better models, that should help resolve some of these artifacts.

**Comment by around-star** [comment]
Thanks for your response @tarun005 , is it possbile that I can collaborate with you on a paper?
