### ISSUE TITLE
Can't run FLAVR

### ISSUE THREAD

**Issue by fzadikian** [tarun005/FLAVR#29]
At first I tried to use Flowframes, but since it gave out an error I tried following your instructions on github. When I tried to run `python interpolate.py --input_video input.mp4 --factor 8 --load_model FLAVR8X.pth` I got a very similar if not identical error message:

`13.000209881905063
Traceback (most recent call last):
  File "interpolate.py", line 133, in <module>
    videoTensor , resizes = video_transform(videoTensor , args.downscale)
  File "interpolate.py", line 121, in video_transform
    videoTensor = transforms(videoTensor)
  File "C:\Users\frangamer1892roblox\MiniConda3\lib\site-packages\torchvision\transforms\transforms.py", line 60, in __call__
    img = t(img)
  File "D:\FLAVR\dataset\transforms.py", line 333, in __call__
    return to_tensor(clip)
  File "D:\FLAVR\dataset\transforms.py", line 107, in to_tensor
    return clip.float().permute(3, 0, 1, 2) / 255.0
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:79] data. DefaultCPUAllocator: not enough memory: you tried to allocate 25944883200 bytes.`

I am not really use what to do now. This are my specs if they help in any way:

[DxDiag.txt](https://github.com/tarun005/FLAVR/files/6767943/DxDiag.txt)

**Comment by tarun005** [comment]
Hi,

As the error message states, you unfortunately do not have enough CPU memory to load all the frames and perform interpolation. Alternatively you can only load four frames at a time into the memory.

**Comment by fzadikian** [comment]
And how would I do that? Thanks.

**Comment by tarun005** [comment]
One way is to save all frame in a folder and write a pytorch dataloader to load only 4 frames at once, like how you generally train a network.

https://pytorch.org/tutorials/beginner/data_loading_tutorial.html

**Comment by fzadikian** [comment]
Thanks, I'll check it out.
