### ISSUE TITLE
question about data augmentation

### ISSUE THREAD

**Issue by XiaoyuShi97** [tarun005/FLAVR#3]
Hi, I am new to pytorch and want to make sure. You use this line to ensure that the augmentations, e.g. randomcrop(), randomflip(), colorjitter(), applied to all frames are identical?
https://github.com/tarun005/FLAVR/blob/8896a0f6e60a6c7b8b08aa973b79b230053690a4/dataset/vimeo90k_septuplet.py#L66

**Comment by XiaoyuShi97** [comment]
According to my experiments, augmentations applied to each frame are different and the difference among frames are huge. I am surprised that this model should converge in such extreme conditions. I will try to train the model to see if I can reproduce the reported metrics.

**Comment by tarun005** [comment]
Closing this due to no further update.
