### ISSUE TITLE
The training batch size of 8x VFI on GoPro

### ISSUE THREAD

**Issue by hityzy1122** [tarun005/FLAVR#31]
Hi,
What is the batch size for training FLAVR for 8x VFI, I see in the paper that it is 32 with the frame size of 512x512. But I train on 8 GPUs(1080Ti whose memory is the same as 2080Ti), I got OOM error and only a batch size of 16 is ok. Besides that, neither random frame order reversal nor random horizontal flipping as augmentation strategies can be found in the GoPro.py. I wonder that can I reproduce the results with this code ?

**Comment by tarun005** [comment]
Hi, thanks for your interest in our work. The GoPro code can be used for inference. For training you have to modify it accordingly adding augmentation etc.

**Comment by hityzy1122** [comment]
Thanks, I will have a try
