### ISSUE TITLE
config.py not affecting interpolate.py behaviour

### ISSUE THREAD

**Issue by Krampfytek** [tarun005/FLAVR#37]
Hey team ! Congrats for the amazing job 

when trying to modify the config file (eg : reducing batch size), it seems to not being affecting the behaviour of the script (interpolate.py) when launched. 

Pretty new to learning python so I maybe misundeerstanding something here, but just in case !

best 

Lucien

**Comment by tarun005** [comment]
interpolate.py is a separate script - it does not use config.py
