### ISSUE TITLE
silent failure

### ISSUE THREAD

**Issue by bmahlbrand** [tarun005/FLAVR#39]
I'm running this on ubuntu w/a 3090 on a video file (4k mkv if it somehow matters, seems to read fine) but it fails silently at https://github.com/tarun005/FLAVR/blob/d2c9ba995aead32b9a57798d8e9aae384428133a/interpolate.py#L115 and the process is simply killed with no error - nothing indicating not enough memory, etc.

Any thoughts on debugging?

**Comment by tarun005** [comment]
Looks like a memory issue. Try batch loading the frames.
