### ISSUE TITLE
About test data of Adobe

### ISSUE THREAD

**Issue by hityzy1122** [tarun005/FLAVR#40]
Hi, thanks for your code, I tested the pretained model of 8x on the test set of gopro and all adobe dataset, and got psnr 31.31 and 31.83 respectively. It is the same as the results reported in paper about gopro, but not adobe(32.20 in paper).
I want to know if the results in paper is not tested on the whole adobe dataset, and could you provide more information about the experiment of 8x interpolation on adobe?
Thanks!

**Comment by tarun005** [comment]
May I know what Adobe dataset are you using?

**Comment by YU-Zhiyang** [comment]
I test on the whole frames extract from https://github.com/shuochsu/DeepVideoDeblurring without center crop.

**Comment by YU-Zhiyang** [comment]
> May I know what Adobe dataset are you using?

I test on the whole frames extract from https://github.com/shuochsu/DeepVideoDeblurring without center crop

**Comment by hityzy1122** [comment]
> May I know what Adobe dataset are you using?

I test on the whole frames extracted from https://github.com/shuochsu/DeepVideoDeblurring without center crop

**Comment by Astrostellar** [comment]
Hi, could you please share the pretrained model? The current links seem to be unavailable. Thanks a lot!
