### ISSUE TITLE
A Colab notebook is available.

### ISSUE THREAD

**Issue by virtualramblas** [tarun005/FLAVR#42]
Hi,

First of all thanks for this amazing work you did and for sharing it with the ML/AI community.
A Colab notebook to do 2X slow-motion filtering is now available in my GitHub space: https://github.com/virtualramblas/python-notebooks-repo/tree/main/Colab/FLAVR
Please let me know if you are interested in it, so I could start a pull request to merge it to this repository.
Thanks.

Best Regards,
Guglielmo

**Comment by tarun005** [comment]
Sure. That will be really helpful. Please raise a PR and I can review soon.

**Comment by virtualramblas** [comment]
@tarun005 PR has been raised.

**Comment by Tsubajashi** [comment]
Could it be that FLAVR wants to copy all frames in RAM first? colab is reacting to a 720p 1 minute 30 seconds, 24fps, clip like this:
`tcmalloc: large alloc 5905612800 bytes == 0x55efce6e2000 @  0x7f7a3ad001e7 0x7f793992d0ce 0x7f7939983cf5 0x7f7939a2c86d 0x7f7939a2d17f 0x7f7939a2d2d0 0x55ed4743a638 0x7f793996e944 0x55ed47438317 0x55ed47438120 0x55ed474abf33 0x55ed474a702f 0x55ed47439aba 0x55ed474a8cd4 0x55ed474a766e 0x55ed47378eb0 0x7f793996e944 0x55ed47438317 0x55ed47438120 0x55ed474abf33 0x55ed474a702f 0x55ed47439aba 0x55ed474ac2c0 0x55ed474a702f 0x55ed47439aba 0x55ed474a7eae 0x55ed474399da 0x55ed474a7eae 0x55ed474a702f 0x55ed474a6d43 0x55ed47571302
`

**Comment by tarun005** [comment]
Yes, that is a limitation in my code currently.

**Comment by lgthappy** [comment]
Hello, I've just started learning, I want to ask: I use a Windows computer to download your code, and then configure python, pytorch, etc., but I don't use ubuntu, all use your pre-processed data, can I use it to see the effect?

**Comment by tarun005** [comment]
Sorry for the incredibly late reply. I have never used or worked with Windows, so I am not sure if this code would work there.
