### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by weiMytian** [tarun005/FLAVR#46]
Hi, author, thank you for sharing the code on GitHub. The code performed well in test, but the PSNR value was always maintained at about 17dB during training. What is the reason?

**Comment by ss00atbupt** [comment]
I‘ve met the same question.
I adjusted my lr, epoch 0 seems good ,psnr is 20. But epoch 1 decreased to about 17. And how is you training now?
![b653e2bb0f26b519b29af14c9570a25](https://user-images.githubusercontent.com/71308854/167073684-c40826bd-e257-453b-967c-d3ecb8617901.png)
![a2150f23193b45435565496755e369d](https://user-images.githubusercontent.com/71308854/167073776-61a3a134-dad6-45c0-b45b-6ecfe0029a1d.png)

**Comment by ss00atbupt** [comment]
Hey, I checked my code.
May I ask your batch_size value?
 I set my lr==0.0002 and batch_size==4, psnr value seems normal now.
Maybe you can try change your batch_size bigger.
Hope it helps.

**Comment by tarun005** [comment]
Can you make sure that the versions of the PyTorch are the same as recommended?
I did not face any such issues at my end.
