### ISSUE TITLE
How to cascade different speed models?

### ISSUE THREAD

**Issue by pango99** [tarun005/FLAVR#49]
Hi Tarun,

from the  #32 issue I know we can cascade different models to make more speed interpolation,such cascade(2x,8x) models to make 16x interpolation, but how to do the cascade? Is that I use 2x model to generate 2x slow sequences firstly,and then apply 8x model to the 2x slow sequences?

**Comment by tarun005** [comment]
Yes, that is how I did for the 64x interpolation. You have to be extra careful near the edge frames though.
