### ISSUE TITLE
Memory leak when running interpolate.py on Windows

### ISSUE THREAD

**Issue by n00mkrad** [tarun005/FLAVR#5]
Running interpolate.py on a 5-second 960x1080 video causes the RAM to fill up constantly at a rate of about 100 mb every 10 seconds.

**Comment by tarun005** [comment]
Hi, 
We haven't tested our code on Windows machines. Did you try downscaling the input video/frames?

**Comment by tarun005** [comment]
We haven't tested our code on Windows machines. Did you try downscaling the input video/frames?

**Comment by n00mkrad** [comment]
This does reduce memory usage but still causes a leak and will fill up the ram after 100-200 frames.

**Comment by n00mkrad** [comment]
I'm pretty sure this is caused because the output frames are all kept in RAM instead of being written to disk.

**Comment by n00mkrad** [comment]
I can confirm that this is caused by ALL output frames being stored in RAM.

**Comment by HeylonNHP** [comment]
Time to write your own implementation :)

**Comment by n00mkrad** [comment]
That's what I did, just not sure if it makes sense to merge the changes back into this repo as it might break other features.

**Comment by tarun005** [comment]
Thanks. Will review PR and merge.
