### ISSUE TITLE
Unable to write out results

### ISSUE THREAD

**Issue by frostedbrain** [tarun005/FLAVR#50]
Hey,

I've managed to get up and running with flavr, right up until the final stage. I'm using a directory with a png sequence in it, which successfully runs through the network. But when it comes to writing it out I simply get:

```
Writing to  in_2xmp4.mp4
in_2xmp4: No such file or directory
Traceback (most recent call last):
  File "interpolate.py", line 164, in <module>
    os.remove(output_video)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'in_2xmp4'
```

I'm reading a sequence of pngs from a directory, using `is_folder` which is great; is there a way to write out a sequence of pngs rather than a video?

**Comment by tarun005** [comment]
Hi,

Sorry for the late reply. We did not encounter this problem. Can you try using some other library for writing out the frames to file?

**Comment by Astrostellar** [comment]
Hi, could you please share the pretrained model? The current links seem to be unavailable. Thanks a lot!
