### ISSUE TITLE
Work with custom videos

### ISSUE THREAD

**Issue by Squeemos** [tarun005/FLAVR#51]
So I wanted to run this on a custom set of videos, but I'm unsure on how I'm supposed to setup the data properly to do so. I currently have another folder inside with my videos, and if I run:
` python test.py --dataset vimeo90K_septuplet --data_root "vimeo90K_septuplet" --load_from "./FLAVR_2x.pth" --n_outputs 1`
where the vimeo90k_septuplet folder just contains my two videos, I get the error
`FileNotFoundError: [Errno 2] No such file or directory: 'vimeo90K_septuplet\\sep_trainlist.txt'`

I'm unsure on how to setup the text file for this, and potentially more issues for setup, but I'm not quite sure where to go. Any help would be really appreciated.

**Comment by tarun005** [comment]
For set of custom videos, can you try using the script `interpolate.py` ?
