### ISSUE TITLE
Question about Training Time

### ISSUE THREAD

**Issue by OliviaWang123456** [tarun005/FLAVR#52]
Hi, thank you for releasing the code.

Your paper writes `We use 8 GPUs and a mini-batch of 32 to train each model, and training is completed in about 36 hours for 2× a` on 2080ti.
But I found it will take at least 5 days on 8 v100 GPUs for 200-epoch training on Vimeo-90K.
Is there some problem ignored by me?

**Comment by tarun005** [comment]
Hi, training time might depend on a lot more things like data loading and GPU sharing. Our training time for 200-epochs varied between 36-48 hours max. 5 days seems like a bit odd, did you check of any other process is occupying the GPU?
