### ISSUE TITLE
custom video，output video size changed

### ISSUE THREAD

**Issue by T0L0ve** [tarun005/FLAVR#53]
Hi，
When I used custom video test interpolate.py I found that the video size had changed.The input size is(960,540) and the output size is (960,536).This is where I find the problem
`downscale = int(downscale * 8)
 resizes = 8 *( H // downscale), 8 *( W // downscale)`
![image](https://user-images.githubusercontent.com/38580985/234755776-4c5076e6-6136-4402-b994-733921ed2079.png)
So I changed the code like this
`resizes = (8 * H // downscale), (8 * W // downscale)`.
But it has an error.
![image](https://user-images.githubusercontent.com/38580985/234756158-fcde4886-6d95-4353-ae73-4281c08e566d.png)
How can I fix this?

**Comment by tarun005** [comment]
The model expects fixed size inputs, and hence renders fixed size outputs. You can add a resize operation after the generation to fix the issue.
