### ISSUE TITLE
First and last frame ignored.

### ISSUE THREAD

**Issue by lucaskuzma** [tarun005/FLAVR#54]
Apparently interpolation ignores the first and last file. Thus 5 input files means 3 are interpolated, yielding (3-1)*4+1 frames, i.e. 9. Should it not be (5-1)*4+1, i.e. 17 frames?

One can replicate the problem with a test image set here: https://github.com/lucaskuzma/FLAVR/blob/main/notebooks/Updated_Fast_Frame_Interpolation_with_FLAVR.ipynb

**Comment by tarun005** [comment]
That is, unfortunately, by design. FLAVR requires atleast 4 frames as input, so the first and last frames cannot be interpolated.
