### ISSUE TITLE
KeyError: 'video_fps'

### ISSUE THREAD

**Issue by kubinka0505** [tarun005/FLAVR#56]
After processing a short 25 FPS video with the `!python interpolate.py --input_video "$VIDEO" --factor 2 --load_model FLAVR_2x.pth` command, I've got an error:

```py
Traceback (most recent call last):
  File "/content/FLAVR/interpolate.py", line 130, in <module>
    videoTensor = video_to_tensor(input_video)
  File "/content/FLAVR/interpolate.py", line 111, in video_to_tensor
    fps = md["video_fps"]
KeyError: 'video_fps'
```

Any way to fix it?

**Comment by tarun005** [comment]
Looks like it has to do something with the versions of torchvision.io. Can you try to match the versions recommended in the repo and let me know if the problem persists?
