### ISSUE TITLE
Unable to access training models

### ISSUE THREAD

**Issue by done-n-dusted** [tarun005/FLAVR#57]
As the title says, I cannot view/download the training models for any of the 2x, 4x, or 8x models. Unable to test those pretrained models. The colab notebook provided asks us to check if gdown works, else, download into your drive and then mount. However, none of the ways work as the links are inaccessible.

**Comment by tarun005** [comment]
Hi, due to an ongoing policy change between UCSD and Google, we are facing severe reductions in our google drive storage allowances - which also unfortunately effected availability of all the pre-trained models. I will try to upload them onto an alternative website and let you know. Sorry for the inconvenience.

**Comment by coattosintetico** [comment]
Hi, I'm running into the same issue. Thanks for your fast response. 

Could we get the weights in the meantime by any other way?

**Comment by lgthappy** [comment]
Hello, I've just started learning, I want to ask: I use a Windows computer to download your code, and then configure python, pytorch, etc., but I don't use ubuntu, all use your pre-processed data, can I use it to see the effect?

**Comment by TQTQliu** [comment]
@tarun005 @done-n-dusted @coattosintetico Hi, I met the same issue. Is there any other way to get the pre-trained weights now?

**Comment by tarun005** [comment]
I am stuck with some logistical hassle, will upload the pre-trained weights before the end of this week, incredibly sorry for the delay.

**Comment by Astrostellar** [comment]
> I am stuck with some logistical hassle, will upload the pre-trained weights before the end of this week, incredibly sorry for the delay.

Any update? The link still seems to be invalid.

**Comment by Willy-Chan** [comment]
^ Also seems to be unworking for me. I would love to use this model in an upcoming research project - would it be possible to send me a copy of the weights?

**Comment by frostedbrain** [comment]
Not the repo owner, but downloaded some time ago. [This is 2x, 4x and 8x](https://file.io/yDSv20077eRl) - originally downloaded 2022/12/28

**Comment by Willy-Chan** [comment]
@frostedbrain Thank you so much! It appears the file associated with the link has been recently deleted - would you mind sending another link?

**Comment by frostedbrain** [comment]
Sure, no worries, [here you go](https://file.io/FRNrTA3UfwWg)!

**Comment by tarun005** [comment]
Updated the repo with new links. Should reproduce the original results - haven't verified myself, but if the results are not being reproduced, let me know and I will look into it. Once again,. sorry for the inconvenience this may have caused.
