### ISSUE TITLE
Unreliable FPS readout causes error

### ISSUE THREAD

**Issue by n00mkrad** [tarun005/FLAVR#6]
When I try to interpolate a video, this error pops up:

```
File "interpolate.py", line 120, in <module>
    videoTensor = video_to_tensor(input_video)
  File "interpolate.py", line 101, in video_to_tensor
    fps = md["video_fps"]
KeyError: 'video_fps'
```

I suspect it fails to read the frame rate for some reason.

This is one of the reasons I am asking for a manual input: https://github.com/tarun005/FLAVR/issues/4

**Comment by n00mkrad** [comment]
As it turns out, this only happens because I mistyped the filename.

There is no error handling for invalid filenames.

**Comment by n00mkrad** [comment]
Fixed in my PR:

https://github.com/tarun005/FLAVR/pull/7

**Comment by tarun005** [comment]
Thanks. Will review PR and merge.
