### ISSUE TITLE
"idxs" is missing frames that videoTensor still had when using "--is_folder"

### ISSUE THREAD

**Issue by n00mkrad** [tarun005/FLAVR#8]
I have 49 video frames, and if I check the length of videoTensor, it matches (49).

However, idxs ends up being only 46 long, resulting in the first and last frame not being interpolated.

**Comment by n00mkrad** [comment]
Update:

This also happens when using a video input, so `--is_folder` doesn't seem to be relevant here.

**Comment by tarun005** [comment]
Yes, that is expected. FLAVR requires at least 4 input frame for reliable interpolation, so the boundary frames cannot be interpolated.

**Comment by n00mkrad** [comment]
Inserting fake entries into the beginning and end of the input file array works fine as a workaround.
